// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NuovoCinemaParadiso.Data;

#nullable disable

namespace NuovoCinemaParadiso.Migrations
{
    [DbContext(typeof(ContestoDb))]
    partial class ContestoDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Abbonamento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Durata")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sconto")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Abbonamenti");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Biglietto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroBiglietti")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OrarioCreazione")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrezzoFinale")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProiezioneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UtenteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProiezioneId");

                    b.HasIndex("UtenteId");

                    b.ToTable("Biglietti");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.GenereMovie", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genere")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeneriMovies");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.GiftCard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Durata")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroMovie")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GiftCard");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.LogAzioni", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Effettuato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdUtente")
                        .HasColumnType("TEXT");

                    b.Property<string>("Messaggio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAzione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogsAzioni");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Movie", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurataMinuti")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenereId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrezzoMovie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenereId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Proiezione", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataProiezione")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TurnoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("SalaId");

                    b.HasIndex("TurnoId");

                    b.ToTable("Proiezioni");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Sala", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Capienza")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipologiaSalaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipologiaSalaId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.TipologiaSala", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaggiorazionePrezzo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TipologieSala");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Turno", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("OraFine")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("OraInizio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Turni");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Utente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AbbonamentoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataInizioAbbonamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataInizioGiftCard")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GiftCardId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PossiedeGiftCard")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeAbbonato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AbbonamentoId");

                    b.HasIndex("GiftCardId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NuovoCinemaParadiso.Models.Utente", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NuovoCinemaParadiso.Models.Utente", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NuovoCinemaParadiso.Models.Utente", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NuovoCinemaParadiso.Models.Utente", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Biglietto", b =>
                {
                    b.HasOne("NuovoCinemaParadiso.Models.Proiezione", "Proiezione")
                        .WithMany("Biglietti")
                        .HasForeignKey("ProiezioneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NuovoCinemaParadiso.Models.Utente", "Utente")
                        .WithMany("Biglietti")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proiezione");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Movie", b =>
                {
                    b.HasOne("NuovoCinemaParadiso.Models.GenereMovie", "Genere")
                        .WithMany("Movies")
                        .HasForeignKey("GenereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genere");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Proiezione", b =>
                {
                    b.HasOne("NuovoCinemaParadiso.Models.Movie", "Movie")
                        .WithMany("Proiezioni")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NuovoCinemaParadiso.Models.Sala", "Sala")
                        .WithMany("Proiezioni")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NuovoCinemaParadiso.Models.Turno", "Turno")
                        .WithMany("Proiezioni")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Sala");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Sala", b =>
                {
                    b.HasOne("NuovoCinemaParadiso.Models.TipologiaSala", "TipologiaSala")
                        .WithMany("Sale")
                        .HasForeignKey("TipologiaSalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipologiaSala");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Utente", b =>
                {
                    b.HasOne("NuovoCinemaParadiso.Models.Abbonamento", "Abbonamento")
                        .WithMany("Utenti")
                        .HasForeignKey("AbbonamentoId");

                    b.HasOne("NuovoCinemaParadiso.Models.GiftCard", "GiftCard")
                        .WithMany("Utenti")
                        .HasForeignKey("GiftCardId");

                    b.Navigation("Abbonamento");

                    b.Navigation("GiftCard");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Abbonamento", b =>
                {
                    b.Navigation("Utenti");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.GenereMovie", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.GiftCard", b =>
                {
                    b.Navigation("Utenti");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Movie", b =>
                {
                    b.Navigation("Proiezioni");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Proiezione", b =>
                {
                    b.Navigation("Biglietti");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Sala", b =>
                {
                    b.Navigation("Proiezioni");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.TipologiaSala", b =>
                {
                    b.Navigation("Sale");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Turno", b =>
                {
                    b.Navigation("Proiezioni");
                });

            modelBuilder.Entity("NuovoCinemaParadiso.Models.Utente", b =>
                {
                    b.Navigation("Biglietti");
                });
#pragma warning restore 612, 618
        }
    }
}
